### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by pokeball99** [CyclopsMC/IntegratedDynamics#1]
i can't tell based on the src. plus there is no compiled version for me to see.
like is it client side? server side? what does this even do?

**Comment by immortaleeb** [comment]
Haha, first of all let me say that I find it quite funny that someone is actually interested in a mod that hasn't even had its first alpha release yet. I'm actually interested in knowing how you came across this repo and why you seem so interested in this mod.

As for your questions: I'm not 100% qualified to answer your questions (I didn't work on this mod), but I'll try my best to tell you what I know, if you need more info I'm sure @rubensworks will be happy to provide you with more details.

_what does this do?_
It's basically an automation mod for minecraft, the short version I always give to people is "It's like applied energistics, but with redstone instead of items". With this mod you can basically build a network that can read "stuff", process the data you got from it and the write that "stuff". A simple example would be to read the strength of some redstone signal, add 1 to it and output the result as another redstone signal or display it on a screen. Other things that you could read for example are the world time, number of players online, information about the liquid in a tank, information about an inventory. All this information is connected in a single network (or multiple networks, if you want certain things separated) and as you can probably guess you can make some complicated stuff with this.

_there is no compiled version for me to see_
Currently work is still being done to release the first version of this mod, that's why no compiled version is available for download. However, a first alpha release shouldn't be too long from now (could be as soon as the end of this week even).
However, if you want to try it out, you should be able to compile it yourself by cloning the repo and using the included gradle script.

**Comment by rubensworks** [comment]
Exactly, see this mod as an integrated mix between bundled redstone, BC gates and AE-style networks.
The API of this mod has been designed in such a way that it is very easy to add new readers/writers for other mods. It would for example be possible (once these mods update), to take some input from Railcraft signals, process in through the network, and changes the mode of a TD itemduct.

And as @immortaleeb has mentioned, you could see this as AE with redstone instead of items, but it goes much further than that. With this mod you are not limited to the 16 redstone int values, but you can expand it to even more values, and even other datatypes on which you can do a number of operations.

For status updates on this mod, you can follow this twitter account: https://twitter.com/kroesermc

**Comment by rubensworks** [comment]
I guess this is as good a time as any to close this issue...
More information can be found on [Curseforge](http://minecraft.curseforge.com/projects/integrated-dynamics).
