### ISSUE TITLE
mechanical squeezer Produces eight times more minerals

### ISSUE THREAD

**Issue by 624980976** [CyclopsMC/IntegratedDynamics#1129]
#### Issue type:

- :bug: Bug 
mechanical squeezer Produces eight times more minerals
![Honeycam 2022-02-03 19-54-06](https://user-images.githubusercontent.com/36782787/152338169-259a16ff-3aa2-4a3a-8e99-c44a27543f2e.gif)

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.18.1-1.10.8
- Minecraft: 1.18.1
- Forge: 39.0.46

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That's intentional.
Happy to change if you can indicate that there's a consensus between other mods to use other ore doubling values.

**Comment by 624980976** [comment]
no, my game only use IntegratedDynamics mod
This rule: 1x Iron Ore = 8x Raw Iron = 8x Iron Ingot is real?
![Honeycam 2022-02-04 12-44-34](https://user-images.githubusercontent.com/36782787/152473313-bb8d0342-75a9-4209-9c3e-106d9b99d8a7.gif)
![Honeycam 2022-02-04 12-45-16](https://user-images.githubusercontent.com/36782787/152473326-5d0a8964-2b34-4b52-9e50-761f34f1507e.gif)

**Comment by rubensworks** [comment]
I've asked around, but there seems to be no consensus on the ore doubling values. Once there is, and if this mod doesn't align with it, I'll be happy to change it. For now, I think the values as-is are good. People can still change the recipes using datapacks if needed.

**Comment by HalJordan** [comment]
Yeah, this isn't changing anything from vanilla or any other pack. Nobody's forcing you to get the 8x processing, and it' easy enough to adjust the recipes if needed. If you don't like it, don't use it?

**Comment by freopt** [comment]
Cyclic has gone with 4-5x ore to raw
fortune 7 averages around 6 raw per ore
personally I think this should be nerfed

**Comment by quietust** [comment]
This change resulted in an infinite ore duplication scenario when combined with Mekanism's Combiner (which can convert 8 raw ore chunks back into an ore block).

Most other mods have balanced their ore multiplications at much lower levels:
* Create: 1.75x for Ore, 1x for Raw Chunk
* Thermal Expansion: 2x for Ore, 1.25x/1.5x (boostable) for Raw Chunk
* Mekanism: 2x/3x/4x/5x for Ore (with increasing time/energy costs), 1.33x/2x/2.66x/3.33x for Raw Chunk
* Immersive Engineering: 2x for Ore, 1.33x/1.5x for Raw Chunk
* Tinkers' Construct: 2.66x for Ore, 1.33x for Raw Chunk

By comparison, Integrated Dynamics is giving 6x/10x for Ore while only requiring minimal effort.

**Comment by rubensworks** [comment]
Thanks for the overview @quietust. I'll look into this again.

**Comment by quietust** [comment]
It should be noted that this issue does **not** strictly apply to Copper Ore, since that has a much higher drop rate in Vanilla to make it usable as a building material:
* Base: 2-5, average 3.5
* Fortune I: 2-10, average 4.666
* Fortune II: 2-15, average 6.125
* Fortune III: 2-20, average 7.7

Some of the mods I mentioned above have similarly adjusted outputs:
* Create: 5.25x for Normal Ore, 7.25x for Deepslate Ore
* Tinkers' Construct: 8x for Ore
(Thermal Expansion, Immersive Engineering, and Mekanism did not have their yields changed, but Mekanism's Combiner demands 20 raw copper chunks in order to make Copper Ore)

As such, the Mechanical Squeezer yield for Copper could probably be adjusted downwards a little bit (e.g. 6/100% + 2/50% + 2/50%, averaging at 8x) and the plain Squeezer yield should be fine as-is.
