### ISSUE TITLE
World Block Importer destroys piston from piston head

### ISSUE THREAD

**Issue by kirjorjos** [CyclopsMC/IntegratedDynamics#1194]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using either an item or block list that does not include a piston (or it's head) (sticky or regular) in a world block importer, it destroys the piston.
#### Steps to reproduce the problem:
Make a variable card list that does not have a piston (or its head). Place said card in a world block importer.  Power a piston such that the head goes in front of the world block importer.

#### Expected behaviour:
The piston is ignored as it is not on the list.

____

#### Versions:

- This mod: 
![image](https://user-images.githubusercontent.com/35607697/180886028-c132bf7d-1694-4540-99ea-933917ec0b40.png)

- Minecraft: 1.18
- Forge: 40.1.41

#### Log file:

[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/9185217/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by met4000** [comment]
After some testing, it seems like this affects the non-"base" blocks of "multi-block" blocks. E.g. the extended heads of pistons, the top block of doors, the feet (i.e. not the head) of beds, and the top of double flowers (not an exclusive list). Breaking the "base" block works as expected. The block reader seems to provide block values for these blocks that do not match (e.g. top door =/= bottom door, although they are both named the same; "oak door").
If a piston is extending while the block importer tries to break it (typically requires the block importer to be set to 1 op per tick), then it seems to break the "moving block" block and result in a headless piston, rather than breaking the piston.

Testing by @kirjorjos on modded blocks also yields similar results for some modded multi-block blocks such as mekanism's digiminer, but not others like immersive engineering's metal press; see discussion in [#integratedmods](https://discord.com/channels/386052815128100865/386054223688630272/1001335119329644564) on the discord server.


The testing I did was with slightly different versions (no mods not listed here were installed);
mod | version
--- | ---
MC | 1.18.2
InTu | 1.8.12
InTu Compat | 1.8.12
Cyclops Core | 1.15.1
Common Capabilities | 2.8.2
Forge | 40.1.0
InProxy | 1.1
InDy | 1.11.6
InDy Compat | 1.11.6
InNBT | 1.5.0
InCr | 1.0.23
InTerm | 1.3.0
InTerm Compat | 1.3.0
InREST | 1.1.5

**Comment by rubensworks** [comment]
Will be fixed in the next release.

In any case, for the specific case of the moving piston, you may have to disable the "Break Block When No Drops" option, since vanilla doesn't drop the piston block for some reason when the piston is in the process of being extended.

**Comment by rubensworks** [comment]
Fixed in [ffe36233ad2720643e1a8b86d41714f02d585971](https://github.com/CyclopsMC/IntegratedTunnels/commit/ffe36233ad2720643e1a8b86d41714f02d585971)
