### ISSUE TITLE
Integrated Dynamics machine recipes not showing up in JEI

### ISSUE THREAD

**Issue by Nevrai** [CyclopsMC/IntegratedDynamics#1210]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Recipes using Integrated Dynamics machines do not show up in [JEI](https://www.curseforge.com/minecraft/mc-mods/jei) (e.g., the recipe for crystallized chorus chunks in the squeezer, the uses of liquid chorus, and so on). This was not the case until recently. I updated JEI a few days ago (9.7.0.226 → 9.7.1.255—latest), and I also updated to the latest version of ID yesterday (1.11.7 → 1.11.9), so I would imagine it’s either an issue with a newer version of JEI or the latest version of ID. (I did also update Forge by one version, but I doubt that’s the cause.)

The changelog for ID 1.11.8 _does_ say that it has been updated to JEI 10, and I’m still using JEI 9 (because a lot of mods don’t work with JEI 10 yet, and it’s still in alpha), so I’d imagine that’s likely the reason that this bug is occurring. If this is the case, hopefully ID can be updated to provide support for JEI 9.7.X again.

**Edit:** I downgraded to ID 1.11.7, and now the recipes show up again. I can confirm that this is an issue caused by 1.11.8 switching which JEI version to support.

#### Steps to reproduce the problem:

Look at the usage for any ID machine or the recipe for any ID item that requires an ID machine in JEI.

____

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.29—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69
* **Integrated Dynamics:** 1.11.9
* **Just Enough Items:** 9.7.1.232 (latest stable release for 1.18.2)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm a bit confused about the release cycle of JEI, and not really sure what version to support now 😅 
@mezz, perhaps you could give some guidance on what to do here?

**Comment by mezz** [comment]
If you build your mod against any old JEI 9 version, your mod should just work fine with JEI 9.7 (or any higher version of JEI 9.x) installed.
There should be no issue here, I will need to see the client log to find out more.

If you want to update, the best version to support right now is JEI 9.7, the latest stable release.
There is also a JEI 10 alpha which adds Fabric support, but it has a few breaking changes in order to support fluids there, so you should avoid updating to it for now.

If you update to the latest version of JEI 9.7 and move away from using deprecated methods, your mod will be compatible with both JEI 9.7 and the JEI 10 alpha versions, and it will also be ready for JEI 11 in Minecraft 1.19.2.

**Comment by mezz** [comment]
You can use this PR as a reference for the kinds of changes you'll make while updating: https://github.com/CyclopsMC/EvilCraft-Compat/pull/9

JEI 9.7, 10, and 11 are mostly the same. You'll probably just need to copy JEI integration from your Minecraft 1.19 branch to here in order to use JEI 9.7.

**Comment by rubensworks** [comment]
Ok, that clarifies things thanks for the input @mezz!

**Comment by Nevrai** [comment]
Thanks for the fix! 🙌
