### ISSUE TITLE
Energy Consumption Rate of Network Reader not changing.

### ISSUE THREAD

**Issue by Vallith** [CyclopsMC/IntegratedDynamics#1216]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using the Network Reader on a network from Integrated Dynamics, everything seems to be updating/working correctly, other than the Energy Consumption rate. It's only ever at 0, even though I do have my batteries/power all running through the network - and things producing/consuming power. I'm playing in the modpack ATM7 To The Sky.

Sorry if I haven't done this correctly, first time. 
#### Steps to reproduce the problem:

1. Create a network with a battery and something consuming that power
2. Place an energy reader reading from one of the cables in that network
3. Look at the "Energy Consumption Rate" aspect

#### Expected behaviour:

I'd expect the number to be updating just as the total energy stored one does as power is consumed.

____

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.11.11
- Minecraft: 1.18.2
- Forge: 40.1.79

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by nskobelevs** [comment]
Can confirm for 1.19.2 as well

**Versions:**

Integrated Dynamics: 1.11.11
Minecraft: 1.19.2
Forge: 43.1.25

**Comment by rubensworks** [comment]
I suspect this is due to a misunderstanding.
The consumption rate aspect will not track the rate of energy of all machines connected to the network. Instead, it will track how much all connected Integrated Dynamics parts consume.
Furthermore, this consumption rate will always be zero if the ID network consumption is set to 0 (which is the default in ID's config file).
