### ISSUE TITLE
feature: "Safe Mode" config option?

### ISSUE THREAD

**Issue by shabble** [CyclopsMC/IntegratedDynamics#125]
I've been having a lot of ID-related crashes lately, and quite a few of them have been persistent, with subsequent restarts crashing immediately or shortly after world loading (playing SSP).

I've been resorting to save-file hackery to hopefully edit out the offending blocks/variable cards, but this is kinda scary and tedious.

If practical, I wonder if a config-file option along the lines of 'safe mode' might be an alternative, which, if enabled, prevents ID from trying to evaluate or resolve any variables or aspects in the world.

In theory, this might allow recovery from an initial crash by toggling this mode, and then erasing or fixing in-game the miscreant components, before reenabling ID.  It might also make it easier to obtain details on the context of the problem that aren't as easily accessible from outside the game/crashlogs.

**Comment by rubensworks** [comment]
Repeated crashes should be impossible, because ID will automatically disable networks after restarting from a crash, which requires resetting the network to make it work again.

Does this mean that you are experiencing crashes in different unrelated networks as well when a series of subsequent crashes occurs?

(Please do report all crashes you encounter if they haven't been reported yet)
