### ISSUE TITLE
crash when using pipes to power a machine in immersive engineering

### ISSUE THREAD

**Issue by TNWanderer** [CyclopsMC/IntegratedDynamics#1277]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft crashes when attempting to place energy exporter on a machine that reqires power

#### Steps to reproduce the problem:

1. required mod Immersive engineering
2. when placing a exergy exporter on the excavator game immediately crashes.  however on at least one machine in mod works as intended.  
3. submitted bug report with other mod earlier.  Dev indicated possibly on this mod's end

#### Expected behaviour:

 expected power to work instead it turned off minecraft.  
____

#### Versions:

- This mod: IntegratedDynamics-1.19.4-1.16.5
- Minecraft: 1.19.4
- Forge: 45.1.0

#### Log file:

https://gist.github.com/TNWanderer/608ad47055a28114a94354b12927f7fa

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I suspect this is a problem on IE's end, more specifically inside the implementation of the excavator's block entity (`getCapability`).

The only thing ID is doing, is invoking `blockEntity.getCapability()` for the PartContainer capability of ID. And for some reason, IE is returning `MutableEnergyStorage`.

Closing this issue for now, but feel free to comment back here if the IE mod author is certain ID is doing something wrong. (but I would be surprised, since this part of our code has been the same for many years)

**Comment by TNWanderer** [comment]
No this is ie's issue, I just noticed yesterday that anyblock placed at that position other then a wire link or the creative accumulator block will cause a crash.

**Comment by rubensworks** [comment]
Ok, thanks for the update!
