### ISSUE TITLE
Fluid connections can not instert or extract fluid to/from a vanilla cauldron. 

### ISSUE THREAD

**Issue by derram** [CyclopsMC/IntegratedDynamics#1306]
Not sure if this should be classified as a feature request instead, but as the title says, ID cables can not seem to interact with a vanilla cauldron.

**Comment by rubensworks** [comment]
Cauldrons are not fluid containers, so that's intended behaviour.
Using a mod like this should fix that: https://www.curseforge.com/minecraft/mc-mods/capable-cauldrons

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/capable-cauldrons">Just a moment...</a></strong></div></blockquote>
