### ISSUE TITLE
Mod-Induced TPS Lag on Server

### ISSUE THREAD

**Issue by grahamfoxrollup** [CyclopsMC/IntegratedDynamics#1319]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

 The profiler indicates that a large portion of the server's resources are being consumed by tasks related to block state management. This is leading to a significant slowdown in-game performance, affecting the overall player experience. It seems that the mod's operations on block states are quite intensive, causing the server to struggle with maintaining smooth gameplay.

I believe this issue might be due to the mod's intensive processing demands, which are overwhelming the server's capacity to handle block management efficiently. I hope this information helps in identifying and resolving the performance issue.

#### Steps to reproduce the problem:

I am unable to provide exact steps to reproduce this issue as it seems to occur under regular gameplay conditions without a specific set of actions. However, to assist in diagnosing and resolving this problem, I can provide the server save file. This file should offer a real-world context of the mod's performance impact on the server.

____

#### Versions:

- This mod: v1.20.3
- Minecraft: 1.20.1
- Forge: 47.2.17

#### Profiler output:

https://spark.lucko.me/Kl4PeAjh3s
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/138266442/976aef15-8fa2-4bef-8e7f-249aee2f621f)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It might be just one (or several) parts leading to excessive tick times.
Could you check the network diagnostics using `/integrateddynamics networkdiagnostics`?
That should help us to identify which operations cause performance issues.

**Comment by SplenectomY** [comment]
I'm having similar issues with ID on my server and would love to help contribute. I've run /integrateddynamics networkdiagnostics ... does this print a report somewhere?

**Comment by grahamfoxrollup** [comment]
> /integrateddynamics networkdiagnostics

getting an unknown command when attempting to use this. does safemode need to be enabled?

**Comment by rubensworks** [comment]
> getting an unknown command when attempting to use this. does safemode need to be enabled?

You must be operator on the server in order to use this command.

After that, the chat will show you a hyperlink on which you can click to view the diagnostics in a web browser window.

**Comment by grahamfoxrollup** [comment]
> > getting an unknown command when attempting to use this. does safemode need to be enabled?
> 
> You must be operator on the server in order to use this command.
> 
> After that, the chat will show you a hyperlink on which you can click to view the diagnostics in a web browser window.

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/138266442/e0d34dad-5bd9-4b78-a23b-508fdea7a39e)

that command isn't recognized regardless of permissions

**Comment by rubensworks** [comment]
You need to use the command as a player, not in the server console.

**Comment by grahamfoxrollup** [comment]
> You need to use the command as a player, not in the server console.

with all do respect, I understand how to do this and I did and that isn't even true.

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/138266442/9ea04485-059e-4435-962d-57563757c69d)

what permissions does integrated dynamics need?

**Comment by rubensworks** [comment]
Hmm, that's weird. You should only require op-permissions: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.20/src/main/java/org/cyclops/integrateddynamics/command/CommandNetworkDiagnostics.java#L42-L48

Can you access any of the other `/integrateddynamics` commands? (e.g. via auto-complete)

**Comment by stripwire** [comment]
I have same issue.
And yay, i found the source of overload!
Overload was caused by the crafter looking for craft items.

Without cards that request crafting, server has stopped printing overload messages, but spark still informs about high load caused by integrated dynamics.
Thanks for `/integrateddynamics networkdiagnostics`

And i don't understand why that not caused CPU load, but just caused low TPS?
May be this related to high memory usage rate?

<details>
<summary>screenshots</summary>
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/6b5fa6cd-734a-4b5e-aa1c-dd1716008a8d">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/6b5fa6cd-734a-4b5e-aa1c-dd1716008a8d">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/6a46ab10-00b5-404b-bfec-9cfadd85ca97)
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/b1470d74-a34e-4515-a9d8-0a25987d97dd">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/7575bd51-b3e3-457a-9b70-adefc703fe53">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/191704f1-e400-4f57-a3d5-b1fb470b2c3d">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/2f981241-00ec-4231-ba84-278f6d707942">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/aa082069-5853-4ed8-b524-ea2f089d5986">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/5764a391-3008-4442-be35-40f6a833a83d">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/90266c5b-b149-4b6a-b7d0-afd27d0d2695">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/654e174e-c639-4553-9a4a-9f41979345e6">
<img src="https://github.com/CyclopsMC/IntegratedDynamics/assets/30651037/85b4513d-091e-4ae8-80ad-3fa260613849">
</details>

**Comment by rubensworks** [comment]
@stripwire Thanks for your findings. Could you create a separate issue for it at https://github.com/CyclopsMC/IntegratedCrafting/ ?

<blockquote><img src="https://opengraph.githubassets.com/5d250c0f5544b9a3af4f385ef886216c4f78d65534f6d0978d85ad7f7bcfa605/CyclopsMC/IntegratedCrafting" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedCrafting">GitHub - CyclopsMC/IntegratedCrafting: Craft stuff in Integrated Dynamics networks</a></strong></div><div>Craft stuff in Integrated Dynamics networks. Contribute to CyclopsMC/IntegratedCrafting development by creating an account on GitHub.</div></blockquote>

**Comment by stripwire** [comment]
@rubensworks 
Oh..
Yesterday that bug was repeats at afternoon, but stopped repeat at evening.
Does it make sense to create issue, if i can't repeat that bug now?

**Comment by rubensworks** [comment]
@stripwire If it occurs again in the future, perhaps you can create an issue then.
