### ISSUE TITLE
Removing/Adding cables/variables/parts causes big client lag spikes

### ISSUE THREAD

**Issue by WhitePhant0m** [CyclopsMC/IntegratedDynamics#1400]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Whenever a cable/part/variable is added/removed, it lags nearby clients for a sec.

#### Steps to reproduce the problem:

All I can say about reproduction steps is that only way I've been able to replicate is with another players setup, I've not been able to replicate this in the same server on my own, nor have I been able to replicate this in a minimal enviroment with only the involved mods.

I did manage to find out that it's the section with the [HNN](https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks) machines that causes lag whenever somethig is changed. But even when I try to replicate the setup(though somewhat minimally), I don't get the lag spikes, or at least I can't spot them.
____

#### Versions:

- This mod: 1.23.5
- Minecraft: 1.21.1
- NeoForge: 21.1.58

#### Profiler output:
https://spark.lucko.me/fXd4TqtYZq
![{DDDCA8D8-6B55-49C5-97C0-64852AFD1B6C}](https://github.com/user-attachments/assets/cd0f7eb3-74bc-4fa9-afa8-afc6aee86ad6)

![image](https://github.com/user-attachments/assets/5bbf5e51-998f-4458-9d9b-214289974f8b)
![image](https://github.com/user-attachments/assets/37f51cc3-8caf-4a26-b92c-b7ae9e98f5d9)
![image](https://github.com/user-attachments/assets/2a9e839f-865d-4a4c-94e5-f6fb8cc2146a)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
From the profiler output, it looks like the overhead is be caused by the logger being set at trace-level (while it's usually at info-level or so).
This can definitely explain lag spikes, and would probably also slow down other parts of the game.
Trace level is usually only used in dev environments, or when attempting to debug something.

Could you check what your log level is?
This can probably be configured in your neoforge config or as an environment variable.

This would also explain why this can't be reproduced in another environment, as the logger level would be set to the default there.

**Comment by WhitePhant0m** [comment]
I can't find that setting in the neoforge configs, and I don't have anything set in my environment variables on my launcher,
and fairly sure it's the same for the other player, as I doubt they have changed pretty much any of the defaults.
