### ISSUE TITLE
Omnidirectional connectors autocrafting issues with AE2

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1425]
#### Issue type:

- :bug: Bug 
![image](https://github.com/user-attachments/assets/4abcf848-005d-46a6-8c29-989cdee12203)
![image](https://github.com/user-attachments/assets/ae49bf3e-4355-4631-9e7c-16645311ee0c)

Creating omnidirectional connector pattern causes the group ID to increase with every tick.

Trying to actually autocraft omnidirectional connectors with AE never finishes and never delivers the item.
____

#### Short description:
NBT in omnidirectional connector messes up with AE2.

#### Steps to reproduce the problem:

1. Try to create omnidirectional connector pattern and in pattern encoder look at output group id.
2. Try to actually craft it.

#### Expected behaviour:

Group id is not increasing and AE can actually craft it.
____

#### Versions:

- This mod: 1.23.19
- Applied Energistics 2: 19.0.23-beta
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.80

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Does this also happen / what happens when you try the alternate recipe using an existing omni-directional connector? That recipe is for crafting for a specific group ID.

**Comment by rubensworks** [comment]
That recipe will always produce an item with different NBT data.
So autocrafting it will probably never work quite right, unless it's possible to disable NBT matching for that specific recipe.
I don't know if something like that is possible in AE2.
But eitherway, this is not something that can be resolved on our end. So I recommend opening an issue in AE2's issue tracker, or asking around on their fora.

Now that I think of it, I'm not sure how Integrated Crafting will handle this recipe.
But if it suffers from the same problem, then it could be fixed by changing the `ignoreDataComponentsForEqualityFilters` config option of Common Capabilities.

Note to self: an alternative solution would be to create an alternative recipe that does not assign group IDs in the NBT data, and instead assigns it on placement or by right-clicking.

**Comment by Jack-McKalling** [comment]
For the feature to assign the ID through right-clicking, see #594

**Comment by Hiranus** [comment]
I like that alternate recipe idea.
From what I gathered AE can't handle this.

**Comment by rubensworks** [comment]
Aha, good catch @Jack-McKalling.
Closing this in favor of #594.

I've moved #594 to accepted feature requests.
It's not high on the priority list for me personally, but any Patreon supporters reading this who are willing to prioritize this one, please let me know.
