### ISSUE TITLE
Squeezer overly sensitive to server TPS on multiplayer

### ISSUE THREAD

**Issue by Saereth** [CyclopsMC/IntegratedDynamics#167]
in our pack we're using the squeezer for the first way to obtain iron essentially. What we've found however is it gets super punishing if the tps is not perfect. 5-10 hops seems to be enough to process an ore at 18-20tps, around 13-15 tps range however some people have reported having to jump over 50 times for a single dust creating a pretty bad user experience. If there is anyway to better sync this it would be greatly appreciated.

**Comment by rubensworks** [comment]
If the server is skipping ticks because of low TPS, there's not much I can do.
The game is made to run on 20 TPS, if you don't reach that, things will simply not work as intended.

I suggest that you look into increasing your TPS.

If you really wanted to, you could use Forestry's squeezer to achieve the same thing, but in machine-form that doesn't require you to jump on it.
