### ISSUE TITLE
MineTweaker support.

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedDynamics#178]
I see that you have added Minetweaker support to V0.7.0! Along with documenting it on the wiki. :tada: 
Do you have an idea for when that will appear on CurseForge? I despise XML and would rather wait a few more days for the MT version to come out rather than spend hours screwing around with XML recipes.
Looking forward to that update! :+1:

**Comment by rubensworks** [comment]
I'm currently in the process of testing, but everything seems to be stable atm, so the latest dev builds should be stable enough to start using.
I _hope_ to start preparing the release this Friday, otherwise it will be for Sunday.

P.S. This could be delayed in case I would discover any major issues, which is unlikely.
