### ISSUE TITLE
server crash when breaking parts to fast

### ISSUE THREAD

**Issue by Sailren** [CyclopsMC/IntegratedDynamics#19]
redeem here: http://paste.ubuntu.com/15416205/

**Comment by rubensworks** [comment]
Thanks for reporting this.
Were you breaking the parts with the wrench or not? If not, this is probably related to #16.

**Comment by Sailren** [comment]
creative mode, just testing stuff

it was like, creative block -> cable ->reader -> chest

**Comment by rubensworks** [comment]
Latest release (0.3.3) should've fixed this. I'll leave this open for a while, just in case it isn't fixed.

**Comment by Aedda** [comment]
I just had a crash on 1.10.2 using version 1.9.4-0.5.1 and I was doing the same thing, the error looks similar but I cannot tell if it is the same problem https://paste.ubuntu.com/23242978/

**Comment by rubensworks** [comment]
@Aedda I assume everything works again as intented when restarting the game?
(You'll have to reset the network (=adding cable to network and breaking it again) because after a network crash it auto-disables itself)

I won't look into this any further, since next update contains a big refactoring of network handling, which should fix all problems related to this one.
