### ISSUE TITLE
Operator tooltips are confusing and not helpful

### ISSUE THREAD

**Issue by ricochet1k** [CyclopsMC/IntegratedDynamics#193]
For example, the "Operator Filter" saying `(Operator -> List) -> List` seems confusing. For anyone familiar with functional programming the parenthesis seem to imply you have to give it a `{Operator -> List)` and get a List out.

It also doesn't help that `Operator` doesn't say anything helpful. `(Any -> Boolean) -> List -> List` would make a lot more sense.

Also, once you start composing these variables they don't keep track of the type they actually represent. It would be much more helpful if you could make the variables compute the type when they are created, and keep that in the tooltip.

**Comment by rubensworks** [comment]
The problem is that this mod evaluates everything very lazy (to reduce server load). As a consequence, the types of operators are not known until evaluation time, which is why they can not be shown in tooltips, as they are only known at the moment of evaluation in the network.

In this case, flexibility goes at the cost of clarity.

I do however intend to implement an advanced logic programmer that is connected to the network with which you can determine the exact types of each variable, so this might improve clarity in these cases.
