### ISSUE TITLE
[1.12] Unstable Variable Store

### ISSUE THREAD

**Issue by Grygon** [CyclopsMC/IntegratedDynamics#239]
I used ID to automate Actually Additions' canola oil upgrade process, but I'm having trouble with it semi-randomly deactivating. Here's a picture of my setup:

![2017-08-12_20 06 42](https://user-images.githubusercontent.com/647846/29245049-28b3d60e-7f9a-11e7-8798-5e0600256018.png)

In short, it reads the fluid block and if its name is "Refined Canola Oil" it sends a redstone signal to the precision dropper, who drops a canola seed. When the block's name is "Crystallized Oil", it sends a redstone signal to the fluid collector who picks it up.

Normally it runs fine, but occasionally when going AFK for a long period of time I come back to no power in my base. The setup is sitting there with the refined canola oil, untriggered to start. In order to start the process again, I have to break the variable store and re-place it, along with inserting all the variable card again--I haven't been able to find another method that works.

I have a similar issue when quitting and re-entering my world, although in this case the readers/writers show an error that the variable could not be found. The same solution (breaking and replacing the variable store) fixes this.

I'm running 0.8.4 on the All the Mods 3 modpack, with Optifine added.

**Comment by rubensworks** [comment]
Sound like a chunk-loading-order-related issue, I'll look into it.

**Comment by Grygon** [comment]
In case it helps, the entire mechanism is located within the same chunk.

**Comment by rubensworks** [comment]
Hmm, then something else must be causing it...

**Comment by maham** [comment]
I'm having something related. Whenever I enter the game I have to break replace my variable storages. Otherwise my setup just spits all my seeds out and ignores my redstone writers. An other way I can fix it is by taking out the variable card and reinserting it in each of the redstone writer in the system.
I have the problem in my automated smeltery too...
Now that I think about it I think all redstone readers/writers are having trouble. The smeltery have a lever to enable molten metal to flow from the smeltery to a tinker tank. I also have a lever to enable flow from the tinker tank to an casting table with an ingot cast. And when I start the game I have to remove->insert the variable cards (or break->place the variable storage) for the levers to work.

MC 1.12.1
Integrated Dynamics 0.8.4
Integrated Tunnels 1.2.5
Forge 14.21.1.2443

**Comment by rubensworks** [comment]
Might be related to #259 

Also, might be related to an "empty tile entity" problem I had before, during world (un)loading.

**Comment by rubensworks** [comment]
I haven't been able to reproduce this issue, but the latest change _should_ resolve it.

This change will be included in next release, if the bug still persists after that, please let me know.
