### ISSUE TITLE
Limit NBT value sizes

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#362]
Large NBT tags can cause network issues when sent from server to client. So make sure we limit the size somehow. Throw an EvaluationException for these.

EDIT: This mainly occurs with NBT value types.

EDIT2: This probably also occurs with other value types that can have large values, such as item lists originating from Colossal Chests (TODO: test with this).

**Comment by josephcsible** [comment]
Related: #211

**Comment by DasBrain** [comment]
Just got always kicked from my server when I logged in because I was displaying the Entity NBT of myself:
https://pastebin.com/tXN7HLA7

Solved that problem by teleporting myself away from the console (logging in and spamming /tp 0 63 0).

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/tXN7HLA7">[17:50:41] [Netty Epoll Server IO #3/ERROR] [FML]: NetworkDispatcher exception   - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
@DasBrain Thanks, I was trying to get a log of that for a while now :-)
