### ISSUE TITLE
Mechanical machines don't work anymore after chunk reload

### ISSUE THREAD

**Issue by MissPotato** [CyclopsMC/IntegratedDynamics#489]
#### Issue type: :bug:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
Batteries do not yield power on chunk reload.

#### Expected behaviour:
On chunk reload batteries should power machines.

#### Actual behaviour:
Doesn't.

#### Steps to reproduce the problem:

1. Place battery with power next to the machine in multiplayer. (Haven't tested singleplayer) 
2. Leave chunks till they unload.
3. Reload chunks

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.0
- CyclopsCore: 0.11.0
- Minecraft: 1.12.2
- Forge: 2587

**Comment by rubensworks** [comment]
Can't reproduce. Are you sure you are powering the battery with a redstone signal?

**Comment by MissPotato** [comment]
No, I'm not. If they require redstone power to provide power, then the bug is behaving incorrectly. 

It seems that when the battery receives a block update in multiplayer they provide energy to machines regardless of redstone.

**Comment by rubensworks** [comment]
> It seems that when the battery receives a block update in multiplayer they provide energy to machines regardless of redstone.

That sounds very unlikely... 

Can you share a screenshot of your setup. I think the machine you are providing energy may just be emitting a redstone signal itself at some point.

**Comment by MissPotato** [comment]
https://giphy.com/gifs/3o751XMdP3lSoCTbxK

Here is a gif detailing everything. The only mods interacting in this setup are tinkers and IntergratedDynamics. 

<blockquote><img src="https://media.giphy.com/media/3o751XMdP3lSoCTbxK/giphy.gif" width="48" align="right"><div><img src="https://giphy.com/static/img/favicon.png" height="14"> GIPHY</div><div><strong><a href="https://media.giphy.com/media/3o751XMdP3lSoCTbxK/giphy.gif">Animated GIF - Find & Share on GIPHY</a></strong></div><div>Discover & share this Animated GIF with everyone you know. GIPHY is how you search, share, discover, and create GIFs.</div></blockquote>

**Comment by rubensworks** [comment]
Ah, ok, so those are ID machines that you are trying to power, that is an important fact to know.

They accept energy from the network, so that part already works as intended. The part that doesn't seem to work properly is that they should indeed keep taking network energy even after a chunk reload.

**Comment by MissPotato** [comment]
Oh sorry, I thought I had specified the setup in the first post.

**Comment by CplPibald** [comment]
I'm unclear how this is supposed to work.  Are mechanical squeezers and drying basins expected to be able to receive energy from the network?  Or do I have to connect an IT energy exporter to it?  

I'm running ID 0.10.2 which has this fix, but my machines aren't taking power when they're not adjacent to the battery.  It does work to attach an IT energy exporter, but it was difficult to figure out how, when the cable already connects to the machine.

**Comment by rubensworks** [comment]
@CplPibald The mechanical machines should take energy from the ID network if there are energy batteries attached to the network (or any other form of energy-providers using energy interfaces).

Otherwise, you can indeed use energy exporters or any kind of RF cable to provide them with energy. This will fill up their internal buffer as seen in the GUI.

**Comment by CplPibald** [comment]
In that case, what am I doing wrong in this setup? 

![](https://i.imgur.com/jTlLM38.png)

Neither machine is charging.  Applying redstone to the battery will charge the squeezer, but not the basin.  Attaching an energy exporter to the top of the machines works as expected.

I can open a new issue if you would prefer, but this might only be user error.

**Comment by rubensworks** [comment]
@CplPibald The internal buffer won't charge in that setup, and doesn't have to.

You should be able to just use the machines as-is. Have you tried that already?

Edit: the cables shouldn't even be necessary.

**Comment by josephcsible** [comment]
Side note: when I first played with the mechanical machines, I was very surprised that the internal buffer didn't charge (instead drawing power from the network only as it needs it), as that seems to be in opposition to how pretty much every other Minecraft machine works. Why did you decide to do it that way?

**Comment by CplPibald** [comment]
Okay, I understand now.  Yes, the machines do work in that configuration.  

It may be a useful enhancement to somehow disable the internal buffer when the machine is drawing from the network.  Possibly remove the buffer meter from the GUI.  Even better, have the GUI reflect the state of the network's battery, so that it correctly indicates which energy supply it's using.

**Comment by rubensworks** [comment]
> as that seems to be in opposition to how pretty much every other Minecraft machine works

The _only_ reason why the internal buffer was added was because of this reason, to be compatible with most other mods. The primary energy source of the machines is the network, which is the primary goal of everything in ID (network-based).

But indeed, I could add something like a tooltip over the energy bar telling that energy is provided by the network as well. (Feel free to open an issue for that)
