### ISSUE TITLE
[Question - 1.12.2] Squeezer Minetweaker and JEI Compat

### ISSUE THREAD

**Issue by KAfable** [CyclopsMC/IntegratedDynamics#497]
#### Issue type:
- :question: Question
____

Sorry for making so many issue related to the Squeezer, but I really liked the mechanics of how it requires a semi Rube Goldberg style of automation with bouncing entities. I'm trying to remove the Squeezer's ore doubling functionality and been mostly unsuccessful with zenscript. 

So going off of here: https://github.com/CyclopsMC/IntegratedDynamics-Compat/blob/62d732b2f709d42fb103c8786689f4d9115b3d05/src/main/java/org/cyclops/integrateddynamicscompat/modcompat/minetweaker/handlers/SqueezerHandler.java

Nothing I do seems to be able to remove recipes that have more than one item output. 
Here's the script: https://hastebin.com/ganozomeri.xml
CraftTweaker Log: https://hastebin.com/opezibewug.md

Adding F's to the end of my float arguments seems to somehow throw off the parser and say it expects another parenthesis, eg if I do:

```
var goldDust = <thermalfoundation:material:1>;
mods.integrateddynamics.Squeezer.removeRecipe(<minecraft:gold_ore>, goldDust, null, goldDust, 0.75f);
```
It will give me the error `Error parsing IntegratedDynamics.zs:33 -- ) expected`.

As for the JEI compat, it says  a .75% chance of a second dust as shown here
![image](https://user-images.githubusercontent.com/26587049/35109190-a6a0725e-fc43-11e7-8b71-1a48b3cadb3d.png)
but ingame testing has this probably closer to 75%, crushing 20 ores has resulted in 34 dust, maybe a typo somewhere.

Versions:
Forge: 2590
CraftTweaker:
Integrated Dynamics: 1.12.2-0.10.1
CyclopsCore: 1.12.2-0.11.1

**Comment by josephcsible** [comment]
The incorrect JEI chance was a bug that's already fixed in git, and will be fixed in the next release.

**Comment by rubensworks** [comment]
@Vyraal1 If you want to disable all recipes, you may want to look into doing this via our recipe XML system. It allows you to override complete recipes sets easily, instead of having to disable each recipe separately. https://github.com/CyclopsMC/IntegratedDynamics/wiki/Recipe-XML

As mentioned by @josephcsible, this bug in the JEI compat will be fixed in next update.

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics">CyclopsMC/IntegratedDynamics</a></strong></div><div>IntegratedDynamics - A Minecraft mod to take full and automated control of your appliances.</div></blockquote>
