### ISSUE TITLE
regarding infinite loops

### ISSUE THREAD

**Issue by Shiruki** [CyclopsMC/IntegratedDynamics#637]
#### Issue type: a request, but not something I'm sure belongs in Feature request

- :question: Question

____

**Comment by rubensworks** [comment]
The infinite recursion error is needed, because otherwise the logic evaluation would get stuck in an infinite loop. What you probably want is something that looks at the _previous_ value of a certain value (previous tick). This can be achieved using the Delayer. (A tutorial is planned for this #613)

> And while I'm here, any word on Integrated Crafting

I'm on holidays right now, but when I get back next week, I'll start working on it :-) If all goes well, I'll release it before the end of this year.

**Comment by Shiruki** [comment]
Thanks for the reply, enjoy your holiday!
