### ISSUE TITLE
Menril Tree Logs are all Sideways in Existing Terrain After Update

### ISSUE THREAD

**Issue by Winrylive** [CyclopsMC/IntegratedDynamics#65]
I know you know about this issue from Reddit, but I live in a Meneglin and I'd really, really like it if my trees didn't look messed up. I've already replaced the texture back to the lovely teal logs, but seriously... please correct backward compatibility of your texture change. Thanks.

**Comment by rubensworks** [comment]
Yes, problem is that either existing trees will be messed up, or I change it and the currently generated (0.5.0) will be messed up.
I guess the latter might be better, since it will affect less people.

I hope to get around to "fixing" this tomorrow.

Note to self: Add a separate block for the filled variant. And add temporary hack that checks the version of the config file, if 0.5.0 then simulate 0.5.0 blockstate metadata translation in unfilled block. (Add a TODO to remove that in the next major version)
