### ISSUE TITLE
Weird behavior with patient bags from Lootbags mod  

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#657]
#### Issue type:

- :bug: Bug

____

#### Short description:

player simulator dupes patient bags when shift clicking the bag into the inventory it got it from

#### Steps to reproduce the problem:

install integrated dynamics and integrated tunnels along side lootbags
1. create a setup like this https://imgur.com/QvLGqVN
2. setup player interface to click with any item 
3. change it to sneak true leave all other options default
4. place patient bag into chest
#### Expected behaviour:

bag should be opened into chest until it turns into a nether star 
____

#### Versions:

- This mod: 0.11.18
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by ghost** [comment]
I also noticed the duped bags vanish if you pick them up

**Comment by Unbox101** [comment]
This is supposed to happen. Those "duped" bags are just the empty opened bags. Normally when you open any loot bag by shift right clicking it on a chest it dumps the contents of the loot bag into the chest and when an empty loot bag is in the players inventory it is automatically deleted. But because you are opening the loot bag from a chest using the player simulator it dumps the contents of the loot bag into the receiving chest and the empty loot bag is left behind and is only automatically deleted if the player picks it up. In any loot bag opener you make using the player simulator you have to set up something to get rid of these empty loot bags.

**Comment by rubensworks** [comment]
Thanks for the information @Unbox101! I'm closing this issue in that case.

If anyone does not agree with this, please let me know.
