### ISSUE TITLE
Let wrench to pop item and drop ID

### ISSUE THREAD

**Issue by borg286** [CyclopsMC/IntegratedDynamics#836]
When cleaning up with the wrench each node (item, fluid, energy) has its own ID and doesn't stack in my inventory, as it is a unique item. Can you make it so shift left clicking pops the item off and drops the ID just like if you painstakingly mined it?

**Comment by Jack-McKalling** [comment]
I think this would be very confusing and accident-prone. If you accidentally click it would delete all that precious data unintentionally. I think it would be better if it requires a different type of item, or a selectable mode for the wrench item. Some warnings or safety is needed to help discourage you from accidentally deleting data (similar to why mining a cable/part takes a long time).

**Comment by borg286** [comment]
I just found that this mod drives for you to have connectors all over the
place. Cleaning them up afterwards ends up with each connector, now unique
with its own ID, taking up its own inventory slot. While I get that you
want to make a connector with its own ID a first class citizen, the vast
majority of the time the card I put in is what makes that connector useful.
I agree that using the wrench on any item and thus deleting it's data would
be bad. I just feel connectors don't deserve to have a unique ID set when
placed. What about making it a button on the connector that turns it from a
non-unique (just crafted) connector, into a unique one with a specific ID?

**Comment by 7eggert** [comment]
The connectors should craft into their brand new form.

**Comment by borg286** [comment]
I guess that my particular use case is too niche. I was using the pipes from this mod to handle my main bus and when doing cleanup of an area I was finding it annoying that my inventory got filled with these connectors rather than, like most mods, collapsing into a single inventory slot. I guess the pipes do collapse but the connectors, something that the rest of the piping items in other mods just automatically create, are a separate item that just adds overhead to using this mod. Needing to craft them, manage them, detach them, recraft them back into vanilla connectors, felt like a severe negative thus balancing out the amazing usefulness of the rest of the mod, so the tedium made the mod balanced. It seems that having connectors with specific IDs and retain them when dropped provides enough value with no easy way to retain that feature while also being intuitive and fool-proof. It makes sense now. Carry on.

**Comment by Jack-McKalling** [comment]
Mono-directional and omni-directional connectors also save their ID when wrenched up, so you can replace them somewhere else.
This allows you to for instance move your existing omni connector without losing its previous group.

I don't believe you can remove the group ID, because each craft gives it a new one, but doing that does remove the ID from the part so it stacks once more with others of the same group ID. The mono connectors don't have a group ID so are even easier to deal with. It's not much to just craft it on its own to remove the data, but if you really think it is too much you could suggest this to be done automatically with a special type of wrench as I explained above. Would be the best method in my opinion.
