### ISSUE TITLE
Inventory and block placing fails after accessing reader GUI from greater than normal distance

### ISSUE THREAD

**Issue by Virgil-the-Freak** [CyclopsMC/IntegratedDynamics#842]
Inventory becomes unstable and no blocks can be placed in world after attempting to access reader GUI from greater than normal distance.  Astral Sorcery perks give greater reach (about 8 blocks I think), and ID works fine when used within the normal 4ish block range, but after that the inventory bugs out (duplicate ghost items, items being removed, items moving positions) and the player becomes unable to place blocks in world.

Reproducing it as easy as getting enough astral sorcery perks to improve reach and trying to access reader GUIs from far away.

Mod version 1.12.2-1.1.4
Minecraft version 1.12.2
Forge version 14.23.5.2847

No crash so no log file, but I have a video demonstrating the problem. https://imgur.com/a/2YtCWMW

**Comment by rubensworks** [comment]
> Reproducing it as easy as getting enough astral sorcery perks to improve reach and trying to access reader GUIs from far away.

Doesn't sounds that easy to me :s Any more details you could share that would enable me to quickly test this in a dev environment?

**Comment by Virgil-the-Freak** [comment]
commands for Astral sorcery to get the perk points needed.

/as maximize [player]
unlocks all progression

/as attune [player] astralsorcery.constellation.aevitas
attunes the player to aevitas

/as exp [player] 3000000
set the player to max level

Then you just have to go and choose perks through the astral tome.  the reach related perks are in the lower left quadrant.

**Comment by rubensworks** [comment]
Moved from #855

-----



#### Issue type:

- :bug: Bug

____

#### Short description:

This is the same bug that Virgil-the-Freak attempted to report, but without the needless hassle to set up astral sorcery. The bug happens while using reach from any mod (Botania's Ring of Far Reach, Astral Sorcery's attunements, Construct's Armory's Gauntlet of Far Reach, etc.). The bug makes it so that you can't move interact with your inventory via the E menu, which is a real pain in the ass.

#### Steps to reproduce the problem:



1. Acquire reach by any method (the above methods are the only I've tested).

2. Attempt to open any tunnel or reader/writer while using reach's extended range. 

3. Experience the bug in the painful glory!

4. Fix via a relog

#### Expected behaviour:



I'd expect to open the inventory for the object, or at least have the menu flash open for a brief moment and then close. What unfortunately happens is the bug.

The bug is signaled to be active when the player inventory gets seemingly randomly jumbled up. This unequips armor and causes things to go in bizarre places like armor slots or the crafting grid. The unequipping of armor may remove flight with certain armor, but I found that it still acts as if the armor is equipped while not allowing flight.

When the bug is activated, it makes the player inventory (accessed by E) unusable by things like inventory tweaks, clicking, etc. It is fixed upon relog but for dummy thicc modpacks like ATM 3 that take a million years to open a world, it's frustrating to do that. The player inventory can be interacted with by doing things like opening a chest, using a terminal, or any other method that shows the player inventory. This does not end the bug, unfortunately. I have made a mini tutorial on the glitch in a small [video.](https://youtu.be/oDa5b9B5kzI)


#### Versions:



- This mod: 1.0.17
- Modpack: All the Mods 3
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by robertmaxton42** [comment]
Hmm. 

I seem to have managed to encounter this bug without having any means of opening an inventory from nonstandard range. It's been a particularly annoying Heisenbug, so I don't have a replication method, though it does indeed tend to occur shortly after using ID terminals. As I'm using a somewhat underpowered machine on a somewhat unstable connection, I suspect lag as the culprit -- by either starting an "open system inventory" screen request, and then moving out of range before it completes, or else starting an "open system inventory" request while my client thinks it's in range, but the server disagrees.
