### ISSUE TITLE
[1.16.4] Drying basin infinitely producing output with Performant

### ISSUE THREAD

**Issue by GarthF** [CyclopsMC/IntegratedDynamics#984]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I placed a drying basin and squeeze next to each other. After squeezing a few logs, I noticed the drying basin kept creating crystalised menril even without any contents. I broke and replaced the basin, same issue persisted. Removing the squeezer has no effect.

#### Steps to reproduce the problem:

1. Place setup to squeeze a menril log
2. Squeeze the log, crystalised menril is created after the fluid changes.
3. remove the crystalised block, wait a few seconds, another block appears in the drying basin.

#### Expected behaviour:

No infinite creation of menril crystal blocks.

____

#### Versions:

- This mod: 1.16.4-1.3.0
- Minecraft: 1.16.5
- Forge: 36.0.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you try again with the latest version?
Also, do you have any other mods installed?

**Comment by GarthF** [comment]
It would seem exiting the game and starting it up again stops the endless cycle (single player instance), but if you squeeze another log, it starts happening again.

I'm running an instance of The Nexus Project Limitless 3 modpack, (TNP 3), 1.9.2 so yeah, a bunch of other mods. I'll try up the versions on Integrated Dynamics.

**Comment by GarthF** [comment]
Can confirm, still experiencing it on Integrated Dynamics 1.4.1 and CyclopsCore 1.11.1

**Comment by rubensworks** [comment]
> Also, do you have any other mods installed?

**Comment by GarthF** [comment]
Well, its the TNP 3 modpack, so yes, +-290 mods

Of the integrated modspace:
Integrated Crafting
Integrated Dynamics
Integrated NBT
Integrated Terminals
Integrated Tunnels

I ran a forge world with JUST integrated dynamics, cyclopscore and common capabilities, and the issue doesn't happen, so likely a mod interaction.

**Comment by rubensworks** [comment]
Thanks for checking. Then I would suggest reporting this to your modpack author.
Should the author still consider this an issue with this mod, then we can reopen this issue.

**Comment by lamoyrl90** [comment]
This same issue is happening in my custom instance. Once I load my world and do a single menril log in the manual squeezer -> drying basin, it continues to produce a new menril block every few seconds.

*edit* I tried removing the squeezer after I got the cycle going, and the drying basin still endlessly produces blocks of menril. Seems like something is repeatedly causing the Drying Basin to produce the output. The filling animation doesn't continually happen, the block of menril just repeatedly pops into the basin. I'm not sure how I would go about checking the contents of the tile's capabilities outside an IDE so I can't say if it's that the machine still thinks it has an input, or if it just is somehow stuck in a loop of setting the output to the last recipe crafted.

*edit again* I'm an idiot and forgot that I'm literally talking about reading the capabilities for a mod that READS CAPABILITIES. I'll see if I can use the mod to diagnose the issue further.

IntDyn 1.4.3
Cyclops 1.11.1
Minecraft 1.16.5
Forge 36.0.1

Modlist: https://pastebin.com/C5CxgKds

If I can provide any more info, lemme know.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/C5CxgKds">Mods:  [✔️] abnormals_core-1.16.4-3.0.6  [✔️] absentbydesign-1.16.4-1.3.1 - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by lamoyrl90** [comment]
Alright, so using the Block Reader to read the Drying Basin's NBT I found this:

Squeezing a Menril Log in the Squeezer adjacent to the Basin causes the Menril fluid to be transferred as expected into the Basin.
The Basin then crafts the Menril Block after the Progress reaches its limit, and the Tank empties itself.
Upon removal of the crafted Menril Block the Progress resets to 0, and although the Tank is now empty, it immediately starts increasing again until the limit is once again reached. At that point it creates a new Menril Block until that one is removed and the process starts over again.

Hope this helps! I'm not sure if you get notified of updates to closed issues, so if there's no reply to this in a couple days, I will open a separate issue to highlight this information.

**Comment by lamoyrl90** [comment]
I think the issue might be in the updateTileEntity() method in tileentity.TileDryingBasin.java

On line 168 the progress is set to 0 but the tile isn't marked as dirty. That might explain why this issue doesn't persist across loads.

**Comment by rubensworks** [comment]
> performant-1.16.2-4-3.30m

@lamoyrl90 There's your problem.
Performant does some game-breaking optimizations.
So **I recommend not using Performant, as it leads to very strange issues such as this one**.

**Comment by lamoyrl90** [comment]
Ah, thanks for figuring out the culprit!

**Comment by hron84** [comment]
@lamoyrl90 since performant is a nice mod for both server and client-side (and I personally like how it makes some heavy modpacks less resource hog), I suggest you to report this issue for them: https://github.com/someaddons/performant_issues/issues

<blockquote><img src="https://avatars.githubusercontent.com/u/38401808?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/someaddons/performant_issues">someaddons/performant_issues</a></strong></div><div>Issue repo for performant. Contribute to someaddons/performant_issues development by creating an account on GitHub.</div></blockquote>

**Comment by Speiger** [comment]
@hron84 honestly performant is not a really good "performance" mod.
Yes it makes mc faster but only by a tiny amount. I was able to have 2k entities on the ground (items) and the server crashed.
Not much lag by mods (pack was 15 mods performant included)

I replaced it with RoadRunner and we got up to 8k entities and the server was running at 60-80MS of lag.
RoadRunner is the lithium port to forge. And runs really well.
